### ISSUE TITLE
Stylistics CSS updates

### ISSUE THREAD

**Issue by michalgren** [Selleo/til#106]
## TASKS:

- [x] - task: 1 - add hover on categories
- [x] - task: 2 - the Whole post should be clickable - now we can click only on the title. Let user to click the whole card add cursor
- [x] - task: 3 - there is a problem with the tooltip triangle - it has a different color
- [x] - task: 4 - add hover on the share button on the blog post
- [x] - task: 5 - don't change color on the number in reaction while hoovering, and probably don't scale the number
- [x] - task: 6 - match profile dropdown to the design from adobe XD, now is smaller than on the design
- [x] - task: 7 - add the heading on user page
- [x] - task: 8 - add hover state to button's
- [x] - task: 9 - fix hover animation on categories 
- [x] - task: 10 - delete Selleo logo from the footer and make the icons to social media smaller

## DETAILS:

1. Add hover on categories like that:
 ![Screenshot 2021-11-29 at 10 16 40](https://user-images.githubusercontent.com/36044370/143840306-1886377d-6a0c-4364-90e4-b2e96d8ec2d4.png)
 
2. the Whole post should be clickable - now we can click only on the title. Let user to click the whole card add cursor: pointer and hover styles to the blog card [design here](https://xd.adobe.com/view/2547df18-c699-40c1-9e26-0651a835b38a-7014/screen/dad9b282-4928-4450-8519-e2b0e84f49db)

3. There is a problem with the tooltip triangle - it has a different color. 
![Screenshot 2021-11-29 at 10 19 58](https://user-images.githubusercontent.com/36044370/143840754-9e7ffe05-cd8d-486f-97b7-83616c27b43a.png)

4. Add hover on the share button on the blog post.

5. Don't change color on the number in reaction while hoovering, and probably don't scale the number. 
https://user-images.githubusercontent.com/36044370/143841553-d3fec758-dd15-40e8-9ebd-e296df69596c.mov

6. Match profile dropdown to the design from adobe XD, now is smaller than on the design.
 ![Screenshot 2021-11-29 at 10 26 05](https://user-images.githubusercontent.com/36044370/143841720-6c5ac9c7-f8d1-4b1c-898b-fbc5c375ad70.png)

7. [Add the heading on user page "My Posts"](https://xd.adobe.com/view/2547df18-c699-40c1-9e26-0651a835b38a-7014/screen/0139f970-6155-4563-9deb-d5a042b5d2be/)

8. Add hover state to button's

9. Fix hover animation on categories 
https://user-images.githubusercontent.com/36044370/143842473-779bdebe-071b-4153-bad9-703ae2c0f07d.mov

10. Delete Selleo logo from the footer and make the icons to social media smaller [like here](https://xd.adobe.com/view/2547df18-c699-40c1-9e26-0651a835b38a-7014/screen/dad9b282-4928-4450-8519-e2b0e84f49db/)
